.\" $Id$
.\"
.\" Man page for the apt-repo program.
.\"
.\" Copyright (c) 2011-2013 Andrey Cherepanov <cas@altlinux.org>
.\"
.\" This software is distributed under the GNU General Public License (GPL)
.\" version 3 or later.
.\"
.Os Linux
.Dd "November 06, 2013"
.ds volume-operating-system Linux
.Dt apt\-repo 8
.\"
.Sh NAME
.Nm apt\-repo
.Nd Manipulate APT repository list
.\"
.Sh SYNOPSIS
.Nm apt\-repo
.Op list
.Op Fl a
.Nm apt\-repo
list
.Op task
.Ar id
.Nm apt\-repo
add
.Ar source
.Nm apt\-repo
rm
.Ar source|all
.Op Ar type
.Nm apt\-repo
clean
.Nm apt\-repo
update
.Nm apt\-repo
test
.Op task
.Ar id
.Nm apt\-repo
.Op Fl h
.Op Fl v
.\"
.Sh DESCRIPTION
The
.Nm apt\-repo
script allow to show, add and remove
.Tn APT
repositories specified by
.Ar source
in
.Xr sources.list 5
format,
.Tn URL
with optional component, branch name or task number.
.Sh OPTIONS
.Bl -tag -width Ds
.It list
Show active repositories in
.Xr sources.list 5
format. If
.Fl a
is specified all available repositories are displayed (inactive are commended by
.Ql #
).
.It list [task] Ar id
Show names of all available packages (except *-debuginfo) in specified by
.Ar id
task repository.
.It add Ar source
Add
.Ar source
to list of active repositories.
.It rm Ar source [<type>]
Remove or comment
.Ar source
if it is active. Special keyword
.Ar all
removes all active sources. The
.Ar all
keyword followed by optional
.Ar <type>
removes all sources of specified type:
.Ql branch
or
.Ql branches
removes all branch sources,
.Ql task
or
.Ql tasks
removes all tasks sources,
.Ql cdrom
or
.Ql cdroms
removes all cdrom sources.
.It clean
Removes all cdrom and task sources.
.It update
Run
.Dl apt\-get update
to update
.Tn APT
cache from active repositories.
.It test [task] Ar id
Install all available packages (except *-debuginfo) from specified by 
.Ar id
task repository.
.It Fl h Fl \-help
Print usage information and quit.
.It Fl v Fl \-version
Print version and quit.
.El
.\"
.Sh "SOURCE FORMAT"
.Ss "APT Source"
Source can be specified in
.Xr sources.list 5
format:
.Pp
.Dl apt\-repo add \*qrpm http://git.altlinux.org/repo/39115/ i586 task\*q
.Pp
Recognized repository types: rpm, rpm-dir and rpm-src. It is allowed to
specify source as separate words. If trailing architecture and component
are missed two lines will be added (current system architecture and
.Ql noarch
) with component
.Ql classic
.
.Ss "URL"
.Tn APT
supports file://, copy://, http://, ftp://, rsync:// and cdrom:// protocols.
.Tn URL
with required protocol may trail optional architecture and one or more
components. If architecture and component are missed two lines will be added
(current system architecture and
.Ql noarch
) with component
.Ql classic .
This form is useful to add branch on mirror server.
.Pp
Example:
.Pp
.Dl apt\-repo add ftp://mirror.yandex.ru/altlinux/p7/branch
.Ss "Absolute Path"
Local directory beginning with
.Ql /
added as hasher repository: with current system architecture and
.Xr hasher
component.
.Pp
.Dl apt\-repo add /opt/repo
.Ss "Branch"
Branch is named repository consist from two parts (current system architecture
and 'noarch'). By default official server is used. Full form:
.Pp
.Dl apt\-repo add branch <name of branch>
.Pp
Keyword
.Ql branch
may be omitted. Example:
.Pp
.Dl apt\-repo add p7
.Pp
Run
.Dl apt\-repo add branch
.Pp
without name of branch displays all available branch names.
.Ss "Task"
Task is small repository for one or more subtask built in http://git.altlinux.org
infrastructure. This source is used to install software for test purpose.
Any task has unique number. Full form:
.Pp
.Dl apt\-repo add task <number of task>
.Pp
Keyword
.Ql task
may be omitted. Example:
.Pp
.Dl apt\-repo add 39115
.\"
.Sh "SEE ALSO"
.Xr sources.list 5 ,
.Xr apt\-cache 8 ,
.Xr apt\-get 8
.\"
.Sh AUTHORS
.An Andrey Cherepanov
.Mt cas@altlinux.org
